version: '3.9'
services:
  backend:
    build: 
      context: .
      dockerfile: src/Dockerfile
      target: development 
    ports:
      - "5000:80"
      - "5050:5050"  
    volumes:
      - ./src:/src # Bind mount untuk sinkronisasi source code
      - ~/.nuget/packages:/root/.nuget/packages # Cache paket NuGet untuk percepat build
      - /src/obj:/src/obj # Hindari konflik file sementara
      - /src/bin:/src/bin # Hindari konflik hasil build
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=true  
      - ConnectionStrings__DefaultConnection=Host=db;Database=tokodb;Port=5432;Username=postgres;Password=123;
    restart: unless-stopped

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: tokodb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432" # Default port PostgreSQL
    volumes:
      - tokodbdata:/var/lib/postgresql/data # Persistent data untuk database
    restart: unless-stopped # Pastikan restart otomatis kalau crash

volumes:
  tokodbdata: # Volume untuk database
